### ISSUE TITLE
Is it working with OpenCV 3.4 in Ubuntu?

### ISSUE THREAD

**Issue by pkr97** [UnaNancyOwen/NuiTrackSDKSample#2]
Hi, Nice to see trhat this repo is updated recently.

Can I expect that this works with OpenCV 3.4 inside Ubuntu 16.04?
Have you tested this?

Thanks...

**Comment by UnaNancyOwen** [comment]
Yes, I think this samples works on Ubuntu. But, It is not tested yet.

**Comment by rbeltranb** [comment]
Not, I am having this error with Ubuntu 18.04:

UVCVideoCapture::open ERROR: can't find device
terminate called after throwing an instance of '
cv::Exception
'
  what():  OpenCV(3.4.4) /home/raub/code/opencv/modules/core/src/matrix_wrap.cpp:130: error: (-213:The function/feature is not implemented) Unknown/unsupported array type in function 'getMat_'
